### ISSUE TITLE
WrappingCollection falls when an item added, collection cleared then that item added again

### ISSUE THREAD

**Issue by dmitrybublik** [LogoFX/logofx-client-mvvm-viewmodel#6]
1. Add item to source collection;
2. Clear source collection;
3. Add this item to source collection again.

If this steps execute fast, the WrappingCollection throws exception in IndexedDictionary: "An item with the same key has already been added".

**Comment by godrose** [comment]
@dmitrybublik ?

**Comment by godrose** [comment]
Consider usage of `ConcurrentDictionary`
